language: go
sudo: false
go:
  - 1.9.x

git:
  depth: 3

before_install:
  - sudo apt-get -qq update
  - go get github.com/BurntSushi/toml
  - go get github.com/Go-SQL-Driver/MySQL
  - go get gopkg.in/telegram-bot-api.v4

install: true


go_import_path: github.com/fnzv/OpenPortNotifier

script:
- bash ci-test.sh
